### ISSUE TITLE
Question: what's the purpose

### ISSUE THREAD

**Issue by jasonkarns** [sergiomasellis/gulp-testem#4]
The readme explains how to set up, but I'm a little lost as to the purpose of this plugin. What value does it provide by being a gulp plugin vs using testem directly? Is there any way to configure this plugin to not require a testem.json config file? What are the pain points this plugin solves?

**Comment by zwacky** [comment]
@jasonkarns you can integrate it in your build process.
e.g. i don't run my tests within my `watch` task, but i'll do so in `build` and `compile`.
